apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deeployment
    name: api-conversao
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
